### ISSUE TITLE
M4 – The CPU frequency is wrong

### ISSUE THREAD

**Issue by vladkens** [vladkens/macmon#11]
The CPU frequency is wrong in my case. It says @ 1MHz. I'm on 15.1.1.

<img width="1496" alt="image" src="https://github.com/user-attachments/assets/e807635e-12ed-45b7-b82b-9e9d54c5e893">

_Originally posted by @plmi in https://github.com/vladkens/macmon/issues/5#issuecomment-2499226740_

**Comment by vladkens** [comment]
Hi, @plmi.

I see you are using an M4, which I have yet had a chance to test on.

Can you give me please debug log by running macmon debug? Like it was in this issue https://github.com/vladkens/macmon/issues/9#issuecomment-2427952348

**Comment by vladkens** [comment]
Hi, @hungrydonkey. Thank you for logs.

Some strange value in `voltage-states1-sram: (f)` and `voltage-states5-sram: (f)`. The M1-M3 chips had a value in Hz, and I converted them to MHz. But now `macmon` shows the values as `0 1 1 1 1 2 2 2 2`, which looks like the values are now stored in KHz (This may have sense because there is a value `4` on P-Core, which would result in an integer overflow - `(2 ** 32 - 1) / 1000 / 1000 = 4294 MHz max`).

Can you check a fix please? Here is latest build: https://github.com/vladkens/macmon/actions/runs/12099700778

Download archive and run macmon binary. If frequencies still showed wrong, can you run `./macmon debug` again on this build – I updated debug log to show raw Hz values.

**Comment by hungrydonkey** [comment]
Ok, here is the new log.
[Uploading M4_debug_with_the_potential_fix.txt…]()

**Comment by hungrydonkey** [comment]
The cpu frequency seems to be right, but the gpu is not. 
![new](https://github.com/user-attachments/assets/c7111a80-10bd-4f4d-873a-b11fc7e18677)

**Comment by vladkens** [comment]
@hungrydonkey Ah yeah, I missed that the GPU values are still in Hz.

Thank you for debugging information. M4 support released in [v0.4.0](https://github.com/vladkens/macmon/releases/tag/v0.4.0). To update, run:

```sh
brew update && brew upgrade macmon
```

**Comment by hungrydonkey** [comment]
> @hungrydonkey Ah yeah, I missed that the GPU values are still in Hz.
> 
> Thank you for debugging information. M4 support released in [v0.4.0](https://github.com/vladkens/macmon/releases/tag/v0.4.0). To update, run:
> 
> ```shell
> brew update && brew upgrade macmon
> ```

@vladkens  Very nice, thank you very much!
