### ISSUE TITLE
FR: configurable refresh interval

### ISSUE THREAD

**Issue by i0ntempest** [vladkens/macmon#16]
Hi,
Would you consider adding changable refresh interval to this tool? For reference `btop` supports from 100ms to seemingly uncapped refresh interval.

**Comment by vladkens** [comment]
Hi, @i0ntempest.

The interval can be changed with `-i` param, but it not persistent unlike color or view. Do you mean to have ability to change interval from TUI with some settings menu?

**Comment by i0ntempest** [comment]
Yup that is what I mean, preferably with hot keys (say + and -).

**Comment by vladkens** [comment]
Hi, @i0ntempest.

Released this in [v0.5.0](https://github.com/vladkens/macmon/releases/tag/v0.5.0)
