### ISSUE TITLE
Formula requires at least a URL

### ISSUE THREAD

**Issue by Flashtheorie** [vladkens/macmon#6]
![Capture d’écran 2024-10-17 à 09 52 09](https://github.com/user-attachments/assets/65fc6667-7652-449c-b61f-a4545cad7ea4)

**Comment by vladkens** [comment]
Hi, @Flashtheorie. What macOS / Apple Silicon (M1, M2, M3) versions you have?

If you run it on Intel processor, tool will not work from Homebrew.

**Comment by Flashtheorie** [comment]
I have a Mac mini M1

**Comment by vladkens** [comment]
I updated [Formula](https://github.com/vladkens/homebrew-tap/commit/dbed121069b662e1b8c104d2081e28c344d0a37a), maybe new OS check is better.

Try to re-install please:

```sh
brew uninstall macmon && brew untap vladkens/tap
```

```sh
brew install vladkens/tap/macmon
```

---

Also, in my experience, the problem can be if you used OS restore from Intel backup. Then Homebrew will continue to be Intel version and may install incorrect packages. Homebrew should be at this path:

```sh
> which brew
/opt/homebrew/bin/brew
```

If path is different likely Intel version installed: https://github.com/orgs/Homebrew/discussions/3223

Also `brew config` can print some details about os versions.

**Comment by Flashtheorie** [comment]
So yes, indeed, when typing "which brew", the path was incorrect, so I just had to add it to the path, it now works, thank you very much.
